### PR TITLE
Double quote env var substitution

### PR DESCRIPTION
**Pull request by ark-1**
### Checklist

- [x] All new jobs, commands, executors, parameters have descriptions
- [x] Examples have been added for any significant new features
- [x] README has been updated, if necessary

### Motivation, issues

Arbitrary JSON response can contain asterisk, for example, which will result in glob expansion, and incorrect data sent. 
Also, all repeated whitespace would be joined.
`{"committer_name": "Starman *     Star"}` -> `{"committer_name": "Starman file1 file2 Star"}`.

### Description

Double quote environment variable substitutions to prevent globbing and word splitting (See [SC2086](https://github.com/koalaman/shellcheck/wiki/SC2086)).

### CODE REVIEW

**Comment by ark-1** [comment]
@KyleTryon the CI seems to be generally broken, unconnected to this PR

**Comment by KyleTryon** [comment]
> @KyleTryon the CI seems to be generally broken, unconnected to this PR

You are correct. Sorry for the different/worse experience here. This orb is running an older model of our CI for Orbs  (prior to the invention of the Orb Development Kit). We can review this manually. 

There is actually an additional issue with the API we need to investigate as well prior to being able to merge this PR.

thank you for the submission 🙏 . There may be large scale changes coming to this orb very shortly, we will keep you in the loop here.

**Comment by ark-1** [comment]
Ok, thanks for the update. Also, would mind adding "hacktoberfest-accepted" label for now? Since October is almost over :) 
Thanks!

**Comment by KyleTryon** [comment]
> hacktoberfest-accepted

That I can, thank you 👍

**Comment by KyleTryon** [comment]
Hello, 

Thank you for your contributions. We have connected with SumoLogic to take over ownership of this orb. We will be archiving this repository shortly.

The new SumoLogic orb and repository can be found here:
 - repo: https://github.com/SumoLogic/sumologic-orb
 - orb: https://circleci.com/developer/orbs/orb/sumologic/sumologic

Ensure to update the orb reference in your config with the orb now under the SumoLogic namespace.

```
orbs:
  sumologic: sumologic/sumologic@2.1.0
```

**Pull request closed without merging**
