### PR TITLE
[semver:minor] workflow-collector.yml update for sending single pipeline payload to Sumo

### PR DESCRIPTION
**Pull request by JKashyap96**
### Checklist

- [x] All new jobs, commands, executors, parameters have descriptions
- [x] Examples have been added for any significant new features
- [x] README has been updated, if necessary

### Motivation, issues

Currently CircleCi ORB sends a single pipeline log data in two payloads for _sourceCategory="circleci/workflow-collector" (examples):

{"pipeline_id":"948f146f-2d81-4e25-9eca-d73cbd05854c","id":"f1274e21-d09a-4dc3-ab8d-19f7db757ecf","name":"build-test-and-deploy","project_slug":"bb/JayantaKashyap/samplerepo","status":"running","started_by":"6b682050-5908-4d68-83b3-392ab22629e9","pipeline_number":13,"created_at":"2021-10-04T12:21:06Z","stopped_at":null,"custom_data":{"env":"production","team":"qa","service":"core-platform"}}

{ "next_page_token": null, "items": [ { "dependencies": [], "job_number": 47, "id": "25c6f867-f8a3-4aac-b41d-fb556990027d", "started_at": "2021-10-04T12:21:11Z", "name": "build", "project_slug": "bb/JayantaKashyap/samplerepo", "status": "success", "type": "build", "stopped_at": "2021-10-04T12:21:16Z" }, { "dependencies": [ "25c6f867-f8a3-4aac-b41d-fb556990027d" ], "job_number": 48, "id": "92e87c4e-bde5-4e8c-a14d-d28dabe6df54", "started_at": "2021-10-04T12:21:20Z", "name": "test", "project_slug": "bb/JayantaKashyap/samplerepo", "status": "success", "type": "build", "stopped_at": "2021-10-04T12:21:28Z" }, { "dependencies": [ "92e87c4e-bde5-4e8c-a14d-d28dabe6df54" ], "job_number": 49, "id": "6ae15804-e63b-4cce-bbdf-5214e2e545d1", "started_at": "2021-10-04T12:21:32Z", "name": "deploy", "project_slug": "bb/JayantaKashyap/samplerepo", "status": "success", "type": "build", "stopped_at": "2021-10-04T12:21:40Z" }, { "job_number": 50, "started_at": "2021-10-04T12:21:45Z", "name": "sumologic/workflow-collector", "project_slug": "bb/JayantaKashyap/samplerepo", "type": "build", "status": "running", "id": "8d5f9d8f-32d9-4f1b-b518-3a8f64859fc1", "dependencies": [ "6ae15804-e63b-4cce-bbdf-5214e2e545d1" ] } ] }

https://jsonformatter.curiousconcept.com/# use this link to view the log in a proper json structure.

One payload contains basic pipeline information and the other contains information about various pipeline stages. They don’t have any field in common to join as well.

But for sumo logic dashboards to work, we need a single payload which contains pipeline information as well its stages.

NOTE : 
_sourceCategory="circleci/job-collector endpoint is giving us the expected information and payload.

### Description

The /sumologic-orb/src/jobs/workflow-collector.yml files needs changes in two places:
We add the JSON object of pipeline items(stages) in the curl command for POST request to Sumo sending basic pipeline information.
We remove(comment out) the curl command for POST request to Sumo sending only the pipeline items(stages) information.

These changes give us the following payload for _sourceCategory="circleci/workflow-collector" (example):

{"pipeline_id":"948f146f-2d81-4e25-9eca-d73cbd05854c","id":"f1274e21-d09a-4dc3-ab8d-19f7db757ecf","name":"build-test-and-deploy","project_slug":"bb/JayantaKashyap/samplerepo","status":"success","started_by":"6b682050-5908-4d68-83b3-392ab22629e9","pipeline_number":13,"created_at":"2021-10-04T12:21:06Z","stopped_at":"2021-10-04T12:22:09Z","custom_data":{"env":"production","team":"qa","service":"core-platform"},"items":[{"dependencies":[],"job_number":47,"id":"25c6f867-f8a3-4aac-b41d-fb556990027d","started_at":"2021-10-04T12:21:11Z","name":"build","project_slug":"bb/JayantaKashyap/samplerepo","status":"success","type":"build","stopped_at":"2021-10-04T12:21:16Z"},{"dependencies":["25c6f867-f8a3-4aac-b41d-fb556990027d"],"job_number":48,"id":"92e87c4e-bde5-4e8c-a14d-d28dabe6df54","started_at":"2021-10-04T12:21:20Z","name":"test","project_slug":"bb/JayantaKashyap/samplerepo","status":"success","type":"build","stopped_at":"2021-10-04T12:21:28Z"},{"dependencies":["92e87c4e-bde5-4e8c-a14d-d28dabe6df54"],"job_number":49,"id":"6ae15804-e63b-4cce-bbdf-5214e2e545d1","started_at":"2021-10-04T12:21:32Z","name":"deploy","project_slug":"bb/JayantaKashyap/samplerepo","status":"success","type":"build","stopped_at":"2021-10-04T12:21:40Z"},{"dependencies":["6ae15804-e63b-4cce-bbdf-5214e2e545d1"],"job_number":50,"id":"8d5f9d8f-32d9-4f1b-b518-3a8f64859fc1","started_at":"2021-10-04T12:21:45Z","name":"sumologic/workflow-collector","project_slug":"bb/JayantaKashyap/samplerepo","status":"success","type":"build","stopped_at":"2021-10-04T12:22:09Z"}]}

So, we are getting the required single payload.

NOTE :
 Carried out this testing by setting up a local environment on a Linux EC2 instance
_sourceCategory="circleci/job-collector endpoint is giving us the expected information and payload
The changes are backward compatible and work for existing SDO dashboards.
reference : https://docs.google.com/document/d/1o9oYWotIhj5ZCRDaOfuvu0688b0PhjQhbqCW8NL8OOo/edit

### CODE REVIEW

**Comment by KyleTryon** [comment]
Hello @JKashyap96 We are working on alternative solutions in the near term that use webhooks rather than the orb. We are still looking into improvements as there is not yet full feature parity but I wanted to share this here: https://circleci.com/docs/2.0/insights-partnerships/#sumo-logic-integration

For this change, my main concern is, the workflow collector is necessary to report the full status of a workflow. Each job individually can report back their status, but if one job in a workflow fails, the rest of the jobs that occur after it will never run. So the workflow collector sits and waits to collect workflow-level information which for now (with the orb) is the only way to determine the full state of the workflow.

However as mentioned above, Webhooks do now send for both jobs and workflows and we can connect that to Sumo directly.

**Comment by JKashyap96** [comment]
Hey @KyleTryon 
We are adopting this orb way of sending logs to Sumo because we need data elements environment_name, service and team which will be sent as custom_data. These are required at Sumo's end for lighting up SDO dashboards.
As for the concern, I tested out a scenario with a failing job in the pipeline and combing the workflow-collector payloads, we get : 

{"pipeline_id":"3cce98a4-8b15-432d-b554-aa78d3fad810","id":"90a2e4e5-9469-4d39-b9c0-69d2efcb456d","name":"build-test-and-deploy","project_slug":"bb/JayantaKashyap/samplerepo","status":"failed","started_by":"6b682050-5908-4d68-83b3-392ab22629e9","pipeline_number":21,"created_at":"2021-10-05T16:09:27Z","stopped_at":"2021-10-05T16:10:20Z","custom_data":{"env":"production","team":"qa","service":"core-platform"},"items":[{"dependencies":[],"job_number":74,"id":"2d75b2bb-6acb-40b8-bf1b-9b4c886ec4df","started_at":"2021-10-05T16:09:31Z","name":"sumologic/workflow-collector","project_slug":"bb/JayantaKashyap/samplerepo","status":"success","type":"build","stopped_at":"2021-10-05T16:10:20Z"},{"dependencies":[],"job_number":75,"id":"ab712647-bfcd-4a76-a7f8-af4bff52df07","started_at":"2021-10-05T16:09:33Z","name":"build","project_slug":"bb/JayantaKashyap/samplerepo","status":"success","type":"build","stopped_at":"2021-10-05T16:09:36Z"},{"dependencies":["ab712647-bfcd-4a76-a7f8-af4bff52df07"],"job_number":76,"id":"ebfdc3b2-214f-4e14-bff4-93ca2bd79cf6","started_at":"2021-10-05T16:09:40Z","name":"test","project_slug":"bb/JayantaKashyap/samplerepo","status":"failed","type":"build","stopped_at":"2021-10-05T16:09:58Z"},{"started_at":null,"name":"deploy","project_slug":"bb/JayantaKashyap/samplerepo","type":"build","status":"blocked","id":"81c4be50-2cc5-43d9-9aad-ed530bb9fde9","dependencies":["ebfdc3b2-214f-4e14-bff4-93ca2bd79cf6"]}]}

which is adequate as per the requirement of the PR.  This payload is giving me the full state of the workflow. 
I hope this clears your doubt.
Have updated the document with a screenshot of the pipeline.

**Comment by KyleTryon** [comment]
Hmm i have just ran the tests again but it doesnt appear the checks reflected the new status. I think this might have something to do with the original branch no longer existing but in either case everything has passed and I will override and merge.

**Comment by JKashyap96** [comment]
Thank you @KyleTryon

**Pull request merged**
